//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INAMU.MesaAyuda.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_NIVEL_ESCALAMIENTO
    {
        public CAT_NIVEL_ESCALAMIENTO()
        {
            this.TBL_ROL = new HashSet<TBL_ROL>();
        }
    
        public int PK_NIVEL_ESCALAMIENTO { get; set; }
        public string VC_NOMBRE { get; set; }
        public string VC_DESCRIPCION { get; set; }
        public int I_ORDEN { get; set; }
    
        public virtual ICollection<TBL_ROL> TBL_ROL { get; set; }
    }
}
