//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INAMU.MesaAyuda.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TICKET_EQUIPO
    {
        public int PK_TICKET_EQUIPO { get; set; }
        public int FK_TICKET { get; set; }
        public int FK_EQUIPO { get; set; }
    
        public virtual TBL_EQUIPO TBL_EQUIPO { get; set; }
        public virtual TBL_TICKET TBL_TICKET { get; set; }
    }
}
