//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INAMU.MesaAyuda.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ACCION
    {
        public TBL_ACCION()
        {
            this.TBL_ROLACCION = new HashSet<TBL_ROLACCION>();
        }
    
        public int PK_ACCION { get; set; }
        public string VC_CONTROLADOR { get; set; }
        public string VC_ACCION { get; set; }
        public string VC_DESCRIPCION { get; set; }
    
        public virtual ICollection<TBL_ROLACCION> TBL_ROLACCION { get; set; }
    }
}
