//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INAMU.MesaAyuda.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EQUIPO
    {
        public TBL_EQUIPO()
        {
            this.TBL_TICKET_EQUIPO = new HashSet<TBL_TICKET_EQUIPO>();
            this.TBL_USUARIO_EQUIPO = new HashSet<TBL_USUARIO_EQUIPO>();
        }
    
        public int PK_EQUIPO { get; set; }
        public int FK_TIPO_EQUIPO { get; set; }
        public string VC_NOMBRE { get; set; }
        public string VC_DESCRIPCION { get; set; }
        public string VC_PLACA { get; set; }
        public string VC_NUMERO_SERIE { get; set; }
        public bool B_ACTIVO { get; set; }
    
        public virtual TBL_VALORCATALOGO TBL_VALORCATALOGO { get; set; }
        public virtual ICollection<TBL_TICKET_EQUIPO> TBL_TICKET_EQUIPO { get; set; }
        public virtual ICollection<TBL_USUARIO_EQUIPO> TBL_USUARIO_EQUIPO { get; set; }
    }
}
