//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INAMU.MesaAyuda.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_UNIDAD
    {
        public TBL_UNIDAD()
        {
            this.TBL_TICKET = new HashSet<TBL_TICKET>();
            this.TBL_USUARIO = new HashSet<TBL_USUARIO>();
        }
    
        public int PK_UNIDAD { get; set; }
        public string VC_CODIGO { get; set; }
        public string VC_DESCRIPCION { get; set; }
        public string VC_PREFIJO { get; set; }
        public Nullable<int> I_NUMERO { get; set; }
        public Nullable<int> I_ANNO { get; set; }
    
        public virtual ICollection<TBL_TICKET> TBL_TICKET { get; set; }
        public virtual ICollection<TBL_USUARIO> TBL_USUARIO { get; set; }
    }
}
