//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INAMU.MesaAyuda.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USUARIO
    {
        public TBL_USUARIO()
        {
            this.TBL_ROLUSUARIO = new HashSet<TBL_ROLUSUARIO>();
            this.TBL_TICKET = new HashSet<TBL_TICKET>();
            this.TBL_TICKET1 = new HashSet<TBL_TICKET>();
            this.TBL_TICKET_SEGUIMIENTO = new HashSet<TBL_TICKET_SEGUIMIENTO>();
            this.TBL_TICKET_ASIGNACION = new HashSet<TBL_TICKET_ASIGNACION>();
            this.TBL_TICKET_ASIGNACION1 = new HashSet<TBL_TICKET_ASIGNACION>();
            this.TBL_USUARIO_EQUIPO = new HashSet<TBL_USUARIO_EQUIPO>();
        }
    
        public int PK_USUARIO { get; set; }
        public string VC_USUARIO { get; set; }
        public System.DateTime DT_FECHAREGISTRO { get; set; }
        public int FK_UNIDAD { get; set; }
        public string VC_NOMBRE { get; set; }
        public string VC_APELLIDO1 { get; set; }
        public string VC_APELLIDO2 { get; set; }
        public byte[] IM_CLAVE { get; set; }
        public byte[] IM_SALT1 { get; set; }
        public byte[] IM_SALT2 { get; set; }
        public bool B_EXTERNO { get; set; }
    
        public virtual ICollection<TBL_ROLUSUARIO> TBL_ROLUSUARIO { get; set; }
        public virtual ICollection<TBL_TICKET> TBL_TICKET { get; set; }
        public virtual ICollection<TBL_TICKET> TBL_TICKET1 { get; set; }
        public virtual ICollection<TBL_TICKET_SEGUIMIENTO> TBL_TICKET_SEGUIMIENTO { get; set; }
        public virtual TBL_UNIDAD TBL_UNIDAD { get; set; }
        public virtual ICollection<TBL_TICKET_ASIGNACION> TBL_TICKET_ASIGNACION { get; set; }
        public virtual ICollection<TBL_TICKET_ASIGNACION> TBL_TICKET_ASIGNACION1 { get; set; }
        public virtual ICollection<TBL_USUARIO_EQUIPO> TBL_USUARIO_EQUIPO { get; set; }
    }
}
