//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INAMU.MesaAyuda.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ROL
    {
        public TBL_ROL()
        {
            this.TBL_ROLACCION = new HashSet<TBL_ROLACCION>();
            this.TBL_ROLUSUARIO = new HashSet<TBL_ROLUSUARIO>();
        }
    
        public int PK_ROL { get; set; }
        public string VC_NOMBRE { get; set; }
        public string VC_DESCRIPCION { get; set; }
        public int FK_NIVEL_ESCALAMIENTO { get; set; }
    
        public virtual CAT_NIVEL_ESCALAMIENTO CAT_NIVEL_ESCALAMIENTO { get; set; }
        public virtual ICollection<TBL_ROLACCION> TBL_ROLACCION { get; set; }
        public virtual ICollection<TBL_ROLUSUARIO> TBL_ROLUSUARIO { get; set; }
    }
}
