//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INAMU.MesaAyuda.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_VALORCATALOGO
    {
        public TBL_VALORCATALOGO()
        {
            this.TBL_BITACORA = new HashSet<TBL_BITACORA>();
            this.TBL_EQUIPO = new HashSet<TBL_EQUIPO>();
            this.TBL_TICKET = new HashSet<TBL_TICKET>();
            this.TBL_TICKET1 = new HashSet<TBL_TICKET>();
            this.TBL_TICKET_ARCHIVO = new HashSet<TBL_TICKET_ARCHIVO>();
            this.TBL_TICKET_ASIGNACION = new HashSet<TBL_TICKET_ASIGNACION>();
        }
    
        public int PK_VALORCATALOGO { get; set; }
        public int FK_CATALOGO { get; set; }
        public string VC_VALOR1 { get; set; }
        public string VC_VALOR2 { get; set; }
    
        public virtual ICollection<TBL_BITACORA> TBL_BITACORA { get; set; }
        public virtual TBL_CATALOGO TBL_CATALOGO { get; set; }
        public virtual ICollection<TBL_EQUIPO> TBL_EQUIPO { get; set; }
        public virtual ICollection<TBL_TICKET> TBL_TICKET { get; set; }
        public virtual ICollection<TBL_TICKET> TBL_TICKET1 { get; set; }
        public virtual ICollection<TBL_TICKET_ARCHIVO> TBL_TICKET_ARCHIVO { get; set; }
        public virtual ICollection<TBL_TICKET_ASIGNACION> TBL_TICKET_ASIGNACION { get; set; }
    }
}
