//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INAMU.MesaAyuda.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TICKET
    {
        public TBL_TICKET()
        {
            this.TBL_TICKET_ARCHIVO = new HashSet<TBL_TICKET_ARCHIVO>();
            this.TBL_TICKET_ASIGNACION = new HashSet<TBL_TICKET_ASIGNACION>();
            this.TBL_TICKET_EQUIPO = new HashSet<TBL_TICKET_EQUIPO>();
            this.TBL_TICKET_SEGUIMIENTO = new HashSet<TBL_TICKET_SEGUIMIENTO>();
        }
    
        public int PK_TICKET { get; set; }
        public int FK_USUARIO_SOLICITA { get; set; }
        public System.DateTime DT_FECHA_CREACION { get; set; }
        public int FK_URGENCIA { get; set; }
        public int FK_UNIDAD_SOLICITA { get; set; }
        public string VC_DESCRIPCION { get; set; }
        public int FK_ESTADO { get; set; }
        public int FK_USUARIO_ASIGNADO { get; set; }
        public int FK_TIPO_PROBLEMA { get; set; }
        public string VC_PLACA_EQUIPO { get; set; }
    
        public virtual ICollection<TBL_TICKET_ARCHIVO> TBL_TICKET_ARCHIVO { get; set; }
        public virtual ICollection<TBL_TICKET_ASIGNACION> TBL_TICKET_ASIGNACION { get; set; }
        public virtual ICollection<TBL_TICKET_EQUIPO> TBL_TICKET_EQUIPO { get; set; }
        public virtual ICollection<TBL_TICKET_SEGUIMIENTO> TBL_TICKET_SEGUIMIENTO { get; set; }
        public virtual TBL_UNIDAD TBL_UNIDAD { get; set; }
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
        public virtual TBL_USUARIO TBL_USUARIO1 { get; set; }
        public virtual TBL_VALORCATALOGO TBL_VALORCATALOGO { get; set; }
        public virtual TBL_VALORCATALOGO TBL_VALORCATALOGO1 { get; set; }
    }
}
