//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INAMU.MesaAyuda.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ROLACCION
    {
        public int PK_ROLACCION { get; set; }
        public int FK_ROL { get; set; }
        public int FK_ACCION { get; set; }
    
        public virtual TBL_ACCION TBL_ACCION { get; set; }
        public virtual TBL_ROL TBL_ROL { get; set; }
    }
}
