//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INAMU.MesaAyuda.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TICKET_SEGUIMIENTO
    {
        public int PK_TICKET_SEGUIMIENTO { get; set; }
        public int FK_TICKET { get; set; }
        public string VC_CONTENIDO { get; set; }
        public int FK_USUARIO_REGISTRA { get; set; }
        public System.DateTime DT_FECHA_EVENTO { get; set; }
    
        public virtual TBL_TICKET TBL_TICKET { get; set; }
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
    }
}
