//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMUN_MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_REGION
    {
        public CAT_REGION()
        {
            this.CAT_DISTRITO = new HashSet<CAT_DISTRITO>();
        }
    
        public int I_IDREGION { get; set; }
        public string VC_DESCRIPCION { get; set; }
    
        public virtual ICollection<CAT_DISTRITO> CAT_DISTRITO { get; set; }
    }
}
